"use strict";

const EXERCISES = [
  { id: "01", code: 'reg = "LT19 KFN"\nhours = 4\nfee = 4.5\n', rest: "Gather the three facts into a vehicle, then print it." },
  { id: "02", code: 'vehicle = {"reg": "LT19 KFN", "hours": 4, "fee": 4.5}\n', rest: "Build vehicle_two, then print it whole and fetch the two requested facts." },
  { id: "03", code: 'vehicle = {"reg": "PK21 RAV", "hours": "4"}\n\nprint(vehicle["hours"] * 2)\n', rest: "Run the given code first. Then fix only the dictionary." },
  { id: "04", code: '# Remove the # from one line at a time.\n# vehicle = {"reg": "LT19 KFN" "hours": 4}\n# vehicle = {"reg" "LT19 KFN", "hours": 4}\n', rest: "Try one punctuation fault at a time for Exercise 04." },
  { id: "05", code: 'vehicle = {"reg": "LT19 KFN", "hours": 4}\nrate = 2.75\n', rest: "Work out the fee, put it into the vehicle, then print the vehicle." },
  { id: "06", code: '# STEP 1 — Build three separate vehicle dictionaries.\n# Do not put them in a list yet. Each variable below should hold ONE complete dictionary.\n# Use these registrations and hours: LT19 KFN, 4; YB70 XCE, 6; PK21 RAV, 1.\n#\n# vehicle_one = {"reg": "LT19 KFN", "hours": 4}\n# vehicle_two = {"reg": "YB70 XCE", "hours": 6}\n# vehicle_three = {"reg": "PK21 RAV", "hours": 1}\n\n# STEP 2 — Gather the three named dictionaries into one list.\n# Put the variable names in the square brackets. Do not write three new dictionaries here.\n#\n# vehicles = [vehicle_one, vehicle_two, vehicle_three]\n# Print one registration from vehicles.\n\n# STEP 3 — Build the second shape: a dictionary keyed by registration.\n# Each registration is the outside key, and its value is a small hours dictionary.\n#\n# vehicles_by_reg = {\n#     "LT19 KFN": {"hours": 4},\n#     "YB70 XCE": {"hours": 6},\n#     "PK21 RAV": {"hours": 1},\n# }\n# Print the hours for LT19 KFN from vehicles_by_reg.\n', rest: "First build three separate vehicle dictionaries, then gather their names into a list and build the registration-keyed shape." },
];
const editor = document.querySelector("#code-editor"), consoleOutput = document.querySelector("#console-output"), runButton = document.querySelector("#run-code"), clearButton = document.querySelector("#clear-console"), status = document.querySelector("#runner-status"), exerciseStrip = document.querySelector("#exercise-strip"), railName = document.querySelector(".rail .brand-name");
let codeMirrorEditor, runnerAvailable = false, currentExercise = "01";
if (railName) railName.textContent = "Building";
function setStatus(message, state = "") { status.textContent = message; status.classList.remove("running", "error"); if (state) status.classList.add(state); }
function editorValue() { return codeMirrorEditor ? codeMirrorEditor.getValue() : editor.value; }
function setEditorValue(value) { if (codeMirrorEditor) { codeMirrorEditor.setValue(value); const codeMirror = editor.nextSibling?.CodeMirror; if (codeMirror) { const lastLine = codeMirror.lastLine(); codeMirror.setCursor({ line: lastLine, ch: codeMirror.getLine(lastLine).length }); } } else { editor.value = value; editor.selectionStart = editor.selectionEnd = value.length; } }
function draftStorageKey(id) { return `supplementary-sheets:${location.pathname}:exercise-${id}`; }
function readDraft(id) { try { return window.localStorage.getItem(draftStorageKey(id)); } catch { return null; } }
function saveDraft(id, value) { try { window.localStorage.setItem(draftStorageKey(id), value); } catch { /* Starter code remains available if browser storage cannot be used. */ } }
function exerciseCode(exercise) { const draft = readDraft(exercise.id); return draft === null ? exercise.code : draft; }
function clearConsole(message) { consoleOutput.classList.remove("error-output"); consoleOutput.textContent = message; setStatus("Ready"); }
function selectExercise(id, { scrollToExercise = true } = {}) { const exercise = EXERCISES.find((item) => item.id === id); if (!exercise) return; if (currentExercise !== id) saveDraft(currentExercise, editorValue()); currentExercise = id; setEditorValue(exerciseCode(exercise)); clearConsole(exercise.rest); exerciseStrip.querySelectorAll("button").forEach((button) => button.setAttribute("aria-pressed", String(button.dataset.exercise === id))); codeMirrorEditor?.focus(); if (scrollToExercise) document.querySelector(`#exercise-${id}`)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
EXERCISES.forEach((exercise) => { const button = document.createElement("button"); button.type = "button"; button.dataset.exercise = exercise.id; button.textContent = exercise.id; button.setAttribute("aria-label", `Exercise ${exercise.id}`); button.setAttribute("aria-pressed", "false"); button.addEventListener("click", () => selectExercise(exercise.id)); exerciseStrip.append(button); });
async function runCode() { if (!runnerAvailable) return; runButton.disabled = true; setStatus("Running", "running"); consoleOutput.classList.remove("error-output"); consoleOutput.textContent = "Running…"; try { const result = await window.browserPython.run(editorValue()); const output = [result.stdout, result.stderr].filter(Boolean).join("").trimEnd(); consoleOutput.textContent = output || "Program finished without output."; if (result.timedOut || result.exitCode !== 0) { consoleOutput.classList.add("error-output"); setStatus(result.timedOut ? "Timed out" : "Check the error", "error"); } else setStatus("Finished"); } catch (error) { consoleOutput.classList.add("error-output"); consoleOutput.textContent = `Python could not start in this browser.\n\n${error.message}`; setStatus("Runner offline", "error"); } finally { runButton.disabled = false; } }
window.addEventListener("python-editor-run", runCode); runButton.addEventListener("click", runCode); clearButton.addEventListener("click", () => clearConsole("Console cleared.")); selectExercise(currentExercise, { scrollToExercise: false });
import("../assets/codemirror-editor.js?v=supplementary-sheets-20260729-plain-enter").then(async ({ createPythonEditor }) => { codeMirrorEditor = await createPythonEditor(editor); setEditorValue(exerciseCode(EXERCISES.find((item) => item.id === currentExercise))); }).catch(() => {});
runButton.disabled = true; setStatus("Preparing Python", "running"); window.browserPython.ready.then(() => { runnerAvailable = true; runButton.disabled = false; setStatus("Ready"); }).catch(() => setStatus("Python unavailable", "error"));
